//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tabeeb.Areas.doctors.languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tabeeb.Areas.doctors.languages.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Your Clinic[optional].
        /// </summary>
        public static string aboutClinic {
            get {
                return ResourceManager.GetString("aboutClinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Doctor.
        /// </summary>
        public static string aboutDoctor {
            get {
                return ResourceManager.GetString("aboutDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex:Faculty of Surgeons, Master of Orthopedics, Cairo University, hand and joint surgery, injuries and fractures of all types, rheumatic and articular diseases, such as hip joints, knees, ankle, shoulder and spine..
        /// </summary>
        public static string aboutDoctorDescrip {
            get {
                return ResourceManager.GetString("aboutDoctorDescrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about doctor at least 30 letters.
        /// </summary>
        public static string aboutDoctorTitle {
            get {
                return ResourceManager.GetString("aboutDoctorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Advice.
        /// </summary>
        public static string addAdvice {
            get {
                return ResourceManager.GetString("addAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Advice In Arabic Language.
        /// </summary>
        public static string addAdviceInArabicLang {
            get {
                return ResourceManager.GetString("addAdviceInArabicLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comment.
        /// </summary>
        public static string addComment {
            get {
                return ResourceManager.GetString("addComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add new time interval.
        /// </summary>
        public static string addNewInterval {
            get {
                return ResourceManager.GetString("addNewInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new service.
        /// </summary>
        public static string addNewService {
            get {
                return ResourceManager.GetString("addNewService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new booking time period.
        /// </summary>
        public static string addNewTimePeriod {
            get {
                return ResourceManager.GetString("addNewTimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Your Appointements To Next Day.
        /// </summary>
        public static string addNextdayAppoint {
            get {
                return ResourceManager.GetString("addNextdayAppoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Your Appointement To Day Of.
        /// </summary>
        public static string addNthDayAppoint {
            get {
                return ResourceManager.GetString("addNthDayAppoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Your Appointements Today.
        /// </summary>
        public static string addTodayAppoint {
            get {
                return ResourceManager.GetString("addTodayAppoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Advice added Successfully.
        /// </summary>
        public static string adviceAddedSuccessfully {
            get {
                return ResourceManager.GetString("adviceAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After accepting from adminstration,Patients can see your profile on Zoor  Doctor.
        /// </summary>
        public static string afterAcceptFromAdminstration {
            get {
                return ResourceManager.GetString("afterAcceptFromAdminstration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to agee on.
        /// </summary>
        public static string agreeOn {
            get {
                return ResourceManager.GetString("agreeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointement Setting.
        /// </summary>
        public static string appointementSetting {
            get {
                return ResourceManager.GetString("appointementSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available time for reserving at general.
        /// </summary>
        public static string availableTime {
            get {
                return ResourceManager.GetString("availableTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex:every day except friday.
        /// </summary>
        public static string availableTimeDescrip {
            get {
                return ResourceManager.GetString("availableTimeDescrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The available time is at least 10 charchters.
        /// </summary>
        public static string availableTimetitle {
            get {
                return ResourceManager.GetString("availableTimetitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to banning you mean that your profile will not bee seen by patients at that time.
        /// </summary>
        public static string banningMeanLose {
            get {
                return ResourceManager.GetString("banningMeanLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to booking type.
        /// </summary>
        public static string bookingType {
            get {
                return ResourceManager.GetString("bookingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to call us on.
        /// </summary>
        public static string callusOn {
            get {
                return ResourceManager.GetString("callusOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t remember my password.
        /// </summary>
        public static string canNotRememberPassword {
            get {
                return ResourceManager.GetString("canNotRememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change number of scedualing dayes.
        /// </summary>
        public static string changeScedualingDays {
            get {
                return ResourceManager.GetString("changeScedualingDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string changeYourPassword {
            get {
                return ResourceManager.GetString("changeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose image that prove your being doctor.
        /// </summary>
        public static string chooseProveImage {
            get {
                return ResourceManager.GetString("chooseProveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here.
        /// </summary>
        public static string clickHere {
            get {
                return ResourceManager.GetString("clickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here to change your password.
        /// </summary>
        public static string clickLinkToChangePassword {
            get {
                return ResourceManager.GetString("clickLinkToChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click on the below link to rest your password.
        /// </summary>
        public static string clickOnResetLink {
            get {
                return ResourceManager.GetString("clickOnResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic Address.
        /// </summary>
        public static string clinicAddress {
            get {
                return ResourceManager.GetString("clinicAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex:sohag,dar elsalam besid hospital of el salam.
        /// </summary>
        public static string clinicAddressDescrip {
            get {
                return ResourceManager.GetString("clinicAddressDescrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clinic address at least 10 letters.
        /// </summary>
        public static string clinicAddressTitle {
            get {
                return ResourceManager.GetString("clinicAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clinic visit.
        /// </summary>
        public static string clinicVisit {
            get {
                return ResourceManager.GetString("clinicVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm password.
        /// </summary>
        public static string confirmPassword {
            get {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consults.
        /// </summary>
        public static string consults {
            get {
                return ResourceManager.GetString("consults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string contactUs {
            get {
                return ResourceManager.GetString("contactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Message Will Be Notified To Our team And Served At The Best Possible Way.
        /// </summary>
        public static string contactUsHint {
            get {
                return ResourceManager.GetString("contactUsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days  starting from now.
        /// </summary>
        public static string daysFromNow {
            get {
                return ResourceManager.GetString("daysFromNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to destrict.
        /// </summary>
        public static string destrict {
            get {
                return ResourceManager.GetString("destrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies is disabled in your browser.
        /// </summary>
        public static string disabledCookiAlert {
            get {
                return ResourceManager.GetString("disabledCookiAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website need cookies,please enable cookies from browser setting,then register or login.
        /// </summary>
        public static string disabledCookieDescrption {
            get {
                return ResourceManager.GetString("disabledCookieDescrption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string doctor {
            get {
                return ResourceManager.GetString("doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor advices.
        /// </summary>
        public static string doctorAdvices {
            get {
                return ResourceManager.GetString("doctorAdvices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination Price.
        /// </summary>
        public static string doctorExaminPrice {
            get {
                return ResourceManager.GetString("doctorExaminPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor page.
        /// </summary>
        public static string doctorPage {
            get {
                return ResourceManager.GetString("doctorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor account on Zoor Doctor.
        /// </summary>
        public static string doctorPageHeader {
            get {
                return ResourceManager.GetString("doctorPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoor Doctor-term of use .
        /// </summary>
        public static string doctorTermOfuse {
            get {
                return ResourceManager.GetString("doctorTermOfuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download From App Store.
        /// </summary>
        public static string downloadApp {
            get {
                return ResourceManager.GetString("downloadApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit my account.
        /// </summary>
        public static string editMyAccount {
            get {
                return ResourceManager.GetString("editMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string emailAddress {
            get {
                return ResourceManager.GetString("emailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username or email that you registered in Zoor Doctor account.
        /// </summary>
        public static string enterusernameOrMailToregister {
            get {
                return ResourceManager.GetString("enterusernameOrMailToregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to evaluation for doctor.
        /// </summary>
        public static string evaluationToDoctor {
            get {
                return ResourceManager.GetString("evaluationToDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evalution.
        /// </summary>
        public static string evalution {
            get {
                return ResourceManager.GetString("evalution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination/Consult.
        /// </summary>
        public static string examinationOrConsult {
            get {
                return ResourceManager.GetString("examinationOrConsult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examinations.
        /// </summary>
        public static string examinations {
            get {
                return ResourceManager.GetString("examinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your examination Fees.
        /// </summary>
        public static string examineFee {
            get {
                return ResourceManager.GetString("examineFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL of your facebook.
        /// </summary>
        public static string facebookurl {
            get {
                return ResourceManager.GetString("facebookurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access to the doctor is based on priority of booking.
        /// </summary>
        public static string firstBookingType {
            get {
                return ResourceManager.GetString("firstBookingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your First name.
        /// </summary>
        public static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex:mohamed.
        /// </summary>
        public static string firstNameEx {
            get {
                return ResourceManager.GetString("firstNameEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the first name is at least 3 charchters and at max 25 characters.
        /// </summary>
        public static string firstNametitle {
            get {
                return ResourceManager.GetString("firstNametitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string fullName {
            get {
                return ResourceManager.GetString("fullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to give view on doctor.
        /// </summary>
        public static string giveViewOnDoctor {
            get {
                return ResourceManager.GetString("giveViewOnDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give Your Comment.
        /// </summary>
        public static string giveYourComment {
            get {
                return ResourceManager.GetString("giveYourComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL of your google-plus.
        /// </summary>
        public static string googleUrl {
            get {
                return ResourceManager.GetString("googleUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to my page.
        /// </summary>
        public static string goToDoctorPage {
            get {
                return ResourceManager.GetString("goToDoctorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home visit.
        /// </summary>
        public static string homeVisit {
            get {
                return ResourceManager.GetString("homeVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can not find the verification message.
        /// </summary>
        public static string icannotFindVerificationMessage {
            get {
                return ResourceManager.GetString("icannotFindVerificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the image has not been updated,please choose valid image.
        /// </summary>
        public static string imgNotUpdated {
            get {
                return ResourceManager.GetString("imgNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is not valid.
        /// </summary>
        public static string imgNotValid {
            get {
                return ResourceManager.GetString("imgNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image of profission.
        /// </summary>
        public static string imgProfession {
            get {
                return ResourceManager.GetString("imgProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info About Doctor.
        /// </summary>
        public static string infoAboutDoctor {
            get {
                return ResourceManager.GetString("infoAboutDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL of your instagram.
        /// </summary>
        public static string instgramUrl {
            get {
                return ResourceManager.GetString("instgramUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string join {
            get {
                return ResourceManager.GetString("join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Last name.
        /// </summary>
        public static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex:khaled solyman.
        /// </summary>
        public static string lastNameEx {
            get {
                return ResourceManager.GetString("lastNameEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the last name is at least 3 charchters and at max 25 characters.
        /// </summary>
        public static string lastnameTitle {
            get {
                return ResourceManager.GetString("lastnameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL of your linkedin.
        /// </summary>
        public static string linkedInUrl {
            get {
                return ResourceManager.GetString("linkedInUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading comments....
        /// </summary>
        public static string loadingComments {
            get {
                return ResourceManager.GetString("loadingComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or register for commenting.
        /// </summary>
        public static string loginForCommenting {
            get {
                return ResourceManager.GetString("loginForCommenting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login now.
        /// </summary>
        public static string loginNow {
            get {
                return ResourceManager.GetString("loginNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid user name and password.
        /// </summary>
        public static string loginValidation {
            get {
                return ResourceManager.GetString("loginValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string logOut {
            get {
                return ResourceManager.GetString("logOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 5 days must be scedualed.
        /// </summary>
        public static string minimusScedualedDays {
            get {
                return ResourceManager.GetString("minimusScedualedDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string mobileNumber {
            get {
                return ResourceManager.GetString("mobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More views.
        /// </summary>
        public static string moreViews {
            get {
                return ResourceManager.GetString("moreViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        public static string myAccount {
            get {
                return ResourceManager.GetString("myAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My appointements.
        /// </summary>
        public static string myAppointement {
            get {
                return ResourceManager.GetString("myAppointement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string myProfile {
            get {
                return ResourceManager.GetString("myProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Services.
        /// </summary>
        public static string myService {
            get {
                return ResourceManager.GetString("myService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string newpassword {
            get {
                return ResourceManager.GetString("newpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no services added by doctor.
        /// </summary>
        public static string noServicesExists {
            get {
                return ResourceManager.GetString("noServicesExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old advices.
        /// </summary>
        public static string oldAdvices {
            get {
                return ResourceManager.GetString("oldAdvices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on schedule.
        /// </summary>
        public static string onSceduale {
            get {
                return ResourceManager.GetString("onSceduale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password has been changed successfully.
        /// </summary>
        public static string passwordChangedSuccessfully {
            get {
                return ResourceManager.GetString("passwordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password must contains at least one uppercase letter and one lowercase letter and 6 letters.
        /// </summary>
        public static string passwordValidation {
            get {
                return ResourceManager.GetString("passwordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Name.
        /// </summary>
        public static string patientName {
            get {
                return ResourceManager.GetString("patientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients views.
        /// </summary>
        public static string patientViews {
            get {
                return ResourceManager.GetString("patientViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to personal image must has equal width and heigth and max size is 1MB.
        /// </summary>
        public static string personalImageTitle {
            get {
                return ResourceManager.GetString("personalImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please communicate with website adminstration and find problem of your banning.
        /// </summary>
        public static string pleaseCommunicateWithTabeebakAboutBanning {
            get {
                return ResourceManager.GetString("pleaseCommunicateWithTabeebakAboutBanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all required fields to complete your profile.
        /// </summary>
        public static string pleaseFillRequiredFields {
            get {
                return ResourceManager.GetString("pleaseFillRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send again.
        /// </summary>
        public static string pleaseTryAgain {
            get {
                return ResourceManager.GetString("pleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pounds.
        /// </summary>
        public static string pounds {
            get {
                return ResourceManager.GetString("pounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are prescribed and defined periods of time that patient can reserve.
        /// </summary>
        public static string prescripedTimeDescr {
            get {
                return ResourceManager.GetString("prescripedTimeDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview arabic profile.
        /// </summary>
        public static string previewArabic_profil {
            get {
                return ResourceManager.GetString("previewArabic profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview english profile.
        /// </summary>
        public static string previewEnglishProfile {
            get {
                return ResourceManager.GetString("previewEnglishProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perview my profile on Zoor Doctor that patients will see.
        /// </summary>
        public static string previewProfile {
            get {
                return ResourceManager.GetString("previewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string previous {
            get {
                return ResourceManager.GetString("previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous views.
        /// </summary>
        public static string prevViews {
            get {
                return ResourceManager.GetString("prevViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to priority to attendance.
        /// </summary>
        public static string priorityToAttendance {
            get {
                return ResourceManager.GetString("priorityToAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profissional Degree.
        /// </summary>
        public static string professionalDegree {
            get {
                return ResourceManager.GetString("professionalDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Professional Title.
        /// </summary>
        public static string professionaltitle {
            get {
                return ResourceManager.GetString("professionaltitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This represents a sign like that is attached to the door of your clinic to clarify specialties for patients.
        /// </summary>
        public static string professionDoctorSign {
            get {
                return ResourceManager.GetString("professionDoctorSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession image is not valid(not updated).
        /// </summary>
        public static string professionImgNotUpdated {
            get {
                return ResourceManager.GetString("professionImgNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession image is not valid.
        /// </summary>
        public static string professionImgNotValid {
            get {
                return ResourceManager.GetString("professionImgNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex:Professor of cardiovascular diseases.
        /// </summary>
        public static string professionTitleDescrip {
            get {
                return ResourceManager.GetString("professionTitleDescrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile timely has been banned by Zoor Doctor adminstration.
        /// </summary>
        public static string profileHasbeenBanned {
            get {
                return ResourceManager.GetString("profileHasbeenBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile has not been updated because of some invalid fields.
        /// </summary>
        public static string profileNotUpdated {
            get {
                return ResourceManager.GetString("profileNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile registration is faild to be added.
        /// </summary>
        public static string profileRegisterAddingFailed {
            get {
                return ResourceManager.GetString("profileRegisterAddingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile with Arabic language.
        /// </summary>
        public static string profileWithArabicLanguage {
            get {
                return ResourceManager.GetString("profileWithArabicLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile with English language.
        /// </summary>
        public static string profileWithEnLanguage {
            get {
                return ResourceManager.GetString("profileWithEnLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is certificate that prove your being a doctor,
        ///                    please picture your certificate and load it&apos;s image so that,we can verify your identity as doctor..
        /// </summary>
        public static string profImageDescription {
            get {
                return ResourceManager.GetString("profImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration has been failed.
        /// </summary>
        public static string registerFaild {
            get {
                return ResourceManager.GetString("registerFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join as doctor With Zoor Doctor Now By Registration.
        /// </summary>
        public static string registerFormHeader {
            get {
                return ResourceManager.GetString("registerFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account on Zoor Doctor.
        /// </summary>
        public static string registerPageHeader {
            get {
                return ResourceManager.GetString("registerPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rememebr me?.
        /// </summary>
        public static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation type for attendance.
        /// </summary>
        public static string reservationType {
            get {
                return ResourceManager.GetString("reservationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -priority on attendance:patients that will come first,will visit first at thier intervals.
        ///                            -on scedual:patient will visit on defined time..
        /// </summary>
        public static string reservationTypeDesc {
            get {
                return ResourceManager.GetString("reservationTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservings Table.
        /// </summary>
        public static string reservingTable {
            get {
                return ResourceManager.GetString("reservingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset password.
        /// </summary>
        public static string reset_password {
            get {
                return ResourceManager.GetString("reset password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rest link has been not sent to my e-mail account.
        /// </summary>
        public static string resetLinkHasNotBeenSent {
            get {
                return ResourceManager.GetString("resetLinkHasNotBeenSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save .
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedualing for.
        /// </summary>
        public static string scedualingFor {
            get {
                return ResourceManager.GetString("scedualingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access to the doctor is based on the prescribed period that patient booked it.
        /// </summary>
        public static string secondBookingType {
            get {
                return ResourceManager.GetString("secondBookingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send me again.
        /// </summary>
        public static string sendMeAgain {
            get {
                return ResourceManager.GetString("sendMeAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoor Doctor will send link on your verified email to reset password.
        /// </summary>
        public static string sendVerificationlink {
            get {
                return ResourceManager.GetString("sendVerificationlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent reset link to.
        /// </summary>
        public static string sentLinkFirstHalf {
            get {
                return ResourceManager.GetString("sentLinkFirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go to your account and click on the reset link to change your password.
        /// </summary>
        public static string sentLinkSeconfHalf {
            get {
                return ResourceManager.GetString("sentLinkSeconfHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string serial {
            get {
                return ResourceManager.GetString("serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operation has been faild at server.
        /// </summary>
        public static string serverOperationProblem {
            get {
                return ResourceManager.GetString("serverOperationProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service name in arabic.
        /// </summary>
        public static string serviceNameAr {
            get {
                return ResourceManager.GetString("serviceNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service name in english.
        /// </summary>
        public static string serviceNameEng {
            get {
                return ResourceManager.GetString("serviceNameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your available times for reservation appointements.
        /// </summary>
        public static string setAppointementsTime {
            get {
                return ResourceManager.GetString("setAppointementsTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your default appointement: note[these apponitement will be the default appointement for all days].
        /// </summary>
        public static string setDefaultAppoint {
            get {
                return ResourceManager.GetString("setDefaultAppoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default appointement .
        /// </summary>
        public static string setDefaultTimePeriods {
            get {
                return ResourceManager.GetString("setDefaultTimePeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type give patients ability to book withen interval of time with attendance based access.
        /// </summary>
        public static string setTimeIntervalsDesc {
            get {
                return ResourceManager.GetString("setTimeIntervalsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more comments.
        /// </summary>
        public static string showMoreComments {
            get {
                return ResourceManager.GetString("showMoreComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password.
        /// </summary>
        public static string showPassword {
            get {
                return ResourceManager.GetString("showPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social media used by Zoor doctor website for communication with you.
        /// </summary>
        public static string socialMediaHint {
            get {
                return ResourceManager.GetString("socialMediaHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social media(optional).
        /// </summary>
        public static string socialMediaOptional {
            get {
                return ResourceManager.GetString("socialMediaOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speciality.
        /// </summary>
        public static string speciality {
            get {
                return ResourceManager.GetString("speciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string statistics {
            get {
                return ResourceManager.GetString("statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sub specialitis.
        /// </summary>
        public static string subSpeciality {
            get {
                return ResourceManager.GetString("subSpeciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are successfully created account on Zoor Doctor.
        /// </summary>
        public static string successAccountCreated {
            get {
                return ResourceManager.GetString("successAccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has successfully changed.
        /// </summary>
        public static string successfullyPasswordChanged {
            get {
                return ResourceManager.GetString("successfullyPasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are successfully created your profile.
        /// </summary>
        public static string successProfileCreated {
            get {
                return ResourceManager.GetString("successProfileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to term of use.
        /// </summary>
        public static string termOfuse {
            get {
                return ResourceManager.GetString("termOfuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your registration, please click on the below link to complete your registration.
        /// </summary>
        public static string thankForRegisterEmail {
            get {
                return ResourceManager.GetString("thankForRegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This may be take some little time time from one to five hours.
        /// </summary>
        public static string thisWilltakeLitteltime {
            get {
                return ResourceManager.GetString("thisWilltakeLitteltime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doctor account on Zoor Doctor.
        /// </summary>
        public static string titleDoctorAccount {
            get {
                return ResourceManager.GetString("titleDoctorAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doctor appointements on Zoor Doctor.
        /// </summary>
        public static string titleDoctorAppointement {
            get {
                return ResourceManager.GetString("titleDoctorAppointement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doctor page on Zoor Doctor.
        /// </summary>
        public static string titleDoctorpage {
            get {
                return ResourceManager.GetString("titleDoctorpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doctor profile on Zoor Doctor.
        /// </summary>
        public static string titleDoctorProfile {
            get {
                return ResourceManager.GetString("titleDoctorProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doctor registration on Zoor Doctor.
        /// </summary>
        public static string titleDoctorRegister {
            get {
                return ResourceManager.GetString("titleDoctorRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter username and password-Zoor Doctor.
        /// </summary>
        public static string titleEnterusernameAndPassword {
            get {
                return ResourceManager.GetString("titleEnterusernameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change your password.
        /// </summary>
        public static string titlePasswordchange {
            get {
                return ResourceManager.GetString("titlePasswordchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remember your password.
        /// </summary>
        public static string titlePasswordremember {
            get {
                return ResourceManager.GetString("titlePasswordremember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profession title at least 10 letters.
        /// </summary>
        public static string titleProfessionaltitle {
            get {
                return ResourceManager.GetString("titleProfessionaltitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabeebak-reset password.
        /// </summary>
        public static string titleResertPassword {
            get {
                return ResourceManager.GetString("titleResertPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to term of use-Zoor Doctor.
        /// </summary>
        public static string titleTermOfuse {
            get {
                return ResourceManager.GetString("titleTermOfuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To complete your profile please download our app from App Store.
        /// </summary>
        public static string toCompleteDownload {
            get {
                return ResourceManager.GetString("toCompleteDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string today {
            get {
                return ResourceManager.GetString("today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today Reservings.
        /// </summary>
        public static string todayReservings {
            get {
                return ResourceManager.GetString("todayReservings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL of your twitter.
        /// </summary>
        public static string twitterUrl {
            get {
                return ResourceManager.GetString("twitterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update operation has been faild.
        /// </summary>
        public static string updateOperationFaild {
            get {
                return ResourceManager.GetString("updateOperationFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating your password.
        /// </summary>
        public static string updatingYourPassword {
            get {
                return ResourceManager.GetString("updatingYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing your username will force you to log out.
        /// </summary>
        public static string usernameChangeAlert {
            get {
                return ResourceManager.GetString("usernameChangeAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verify your account-Zoor Doctor.
        /// </summary>
        public static string verifyAccount {
            get {
                return ResourceManager.GetString("verifyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please go to your email.
        /// </summary>
        public static string verifyAccountPartOne {
            get {
                return ResourceManager.GetString("verifyAccountPartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and verifiy your account.
        /// </summary>
        public static string verifyAccountPartTwo {
            get {
                return ResourceManager.GetString("verifyAccountPartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are waiting the accepte from adminstration of Zoor Doctor until making sure of your data.
        /// </summary>
        public static string waitingAcceptfromAdmin {
            get {
                return ResourceManager.GetString("waitingAcceptfromAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time that patients will wait before visit.
        /// </summary>
        public static string waitingTimeDesc {
            get {
                return ResourceManager.GetString("waitingTimeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting time required.
        /// </summary>
        public static string waitingTimerequired {
            get {
                return ResourceManager.GetString("waitingTimerequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcom Dr..
        /// </summary>
        public static string welcom {
            get {
                return ResourceManager.GetString("welcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what mean by priority on attendance/on sceduale.
        /// </summary>
        public static string whatMeanByReservationtype {
            get {
                return ResourceManager.GetString("whatMeanByReservationtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Appointement in general.
        /// </summary>
        public static string workAppointements {
            get {
                return ResourceManager.GetString("workAppointements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Medical Advice.
        /// </summary>
        public static string writeMedicalAdvice {
            get {
                return ResourceManager.GetString("writeMedicalAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have.
        /// </summary>
        public static string youHave {
            get {
                return ResourceManager.GetString("youHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to make sure that you paid all worths for website(may be the root of problem).
        /// </summary>
        public static string youNotPaidForWebsite {
            get {
                return ResourceManager.GetString("youNotPaidForWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Comment.
        /// </summary>
        public static string yourComment {
            get {
                return ResourceManager.GetString("yourComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL of your youtube.
        /// </summary>
        public static string youtubeUrl {
            get {
                return ResourceManager.GetString("youtubeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoor Doctor.
        /// </summary>
        public static string zoorDoctor {
            get {
                return ResourceManager.GetString("zoorDoctor", resourceCulture);
            }
        }
    }
}
