//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tabeeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public string name { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public System.DateTime dateOfJoin { get; set; }
        public string mail { get; set; }
        public string type { get; set; }
        public byte periority { get; set; }
        public string image { get; set; }
        public Nullable<System.DateTime> lastDoctorComplainsViewedDate { get; set; }
        public Nullable<System.DateTime> lastPatientComplainsVieweddate { get; set; }
        public Nullable<System.DateTime> lastGeneralComplainViewedDate { get; set; }
    }
}
