//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tabeeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class advice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public advice()
        {
            this.commentOnAdvices = new HashSet<commentOnAdvice>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid doctorID { get; set; }
        public string adviceContent { get; set; }
        public System.DateTime dateOfJoin { get; set; }
    
        public virtual doctor doctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<commentOnAdvice> commentOnAdvices { get; set; }
    }
}
