//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tabeeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class advRelatedPage
    {
        public byte advID { get; set; }
        public byte pageID { get; set; }
        public int id { get; set; }
    
        public virtual adv adv { get; set; }
        public virtual page page { get; set; }
    }
}
