//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tabeeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointement
    {
        public System.Guid doctorID { get; set; }
        public string interval { get; set; }
        public Nullable<System.DateTime> dateOfBooking { get; set; }
        public System.Guid id { get; set; }
    
        public virtual doctor doctor { get; set; }
    }
}
