//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tabeeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class commentOnAdvice
    {
        public System.Guid patientID { get; set; }
        public System.Guid adviceID { get; set; }
        public System.Guid id { get; set; }
        public string comment { get; set; }
        public bool like { get; set; }
        public bool share { get; set; }
        public bool seen { get; set; }
    
        public virtual advice advice { get; set; }
        public virtual patient patient { get; set; }
    }
}
