//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tabeeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctorInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doctorInfo()
        {
            this.services = "[]";
            this.urls = "\"[]\"";
            this.numberOfScedualedDayes = 31;
        }
    
        public System.Guid doctorID { get; set; }
        public string fnameEng { get; set; }
        public string lnameEng { get; set; }
        public byte education { get; set; }
        public bool type { get; set; }
        public bool stat { get; set; }
        public string profTitleEng { get; set; }
        public string aboutDocEng { get; set; }
        public string aboutClnicEng { get; set; }
        public string fnameAr { get; set; }
        public string lnameAr { get; set; }
        public string profTitleAr { get; set; }
        public string aboutDocAr { get; set; }
        public string aboutClnicAr { get; set; }
        public bool reservingType { get; set; }
        public string clinicAddressEng { get; set; }
        public string clinicAddressAr { get; set; }
        public short examinFees { get; set; }
        public string image { get; set; }
        public string availableTimeEng { get; set; }
        public string availableTimeAr { get; set; }
        public string services { get; set; }
        public string urls { get; set; }
        public bool profileIsAccepted { get; set; }
        public byte numberOfScedualedDayes { get; set; }
        public byte waitingTime { get; set; }
    
        public virtual doctor doctor { get; set; }
    }
}
