//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tabeeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resetPasswordRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public resetPasswordRequest()
        {
            this.entity = true;
        }
    
        public System.Guid id { get; set; }
        public System.Guid userID { get; set; }
        public System.DateTime requestTime { get; set; }
        public bool entity { get; set; }
        public string phoneCode { get; set; }
    }
}
