//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tabeeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserving
    {
        public System.Guid doctorID { get; set; }
        public Nullable<System.Guid> patientID { get; set; }
        public System.DateTime reservingDate { get; set; }
        public bool visitType { get; set; }
        public string patientName { get; set; }
        public string phone { get; set; }
        public string interval { get; set; }
        public System.Guid id { get; set; }
        public bool confirmed { get; set; }
        public bool done { get; set; }
    
        public virtual doctor doctor { get; set; }
        public virtual patient patient { get; set; }
    }
}
