//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tabeeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subSpeciality
    {
        public byte id { get; set; }
        public string nameEng { get; set; }
        public byte spID { get; set; }
        public string nameAr { get; set; }
        public string descriptionAr { get; set; }
        public string descriptionEng { get; set; }
        public string img { get; set; }
    }
}
