//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tabeeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class websiteInformation
    {
        public string serviceNumber { get; set; }
        public string serviceEtisalat { get; set; }
        public string serviceVodafon { get; set; }
        public string serviceMobinil { get; set; }
        public string mainPageImages { get; set; }
    }
}
