//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tabeeb.Areas.users.languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tabeeb.Areas.users.languages.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  you can send your suggestion or point of view about site.
        /// </summary>
        public static string aboutCallUs {
            get {
                return ResourceManager.GetString("aboutCallUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at most 300 letters only arabic text allowed.
        /// </summary>
        public static string aboutClinicValidationAr {
            get {
                return ResourceManager.GetString("aboutClinicValidationAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at most 300 letters only english text allowed.
        /// </summary>
        public static string aboutClinicValidationEng {
            get {
                return ResourceManager.GetString("aboutClinicValidationEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The aim of our company to access and reservation by doctors easy, simple and highly efficient, saving time and effort in the patient and reduce congestion.
        /// </summary>
        public static string aboutDocReserve {
            get {
                return ResourceManager.GetString("aboutDocReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about doctor at least 20 letters and at most 200 letters.
        /// </summary>
        public static string aboutDoctorLength {
            get {
                return ResourceManager.GetString("aboutDoctorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about doctor is required.
        /// </summary>
        public static string aboutDoctorrequired {
            get {
                return ResourceManager.GetString("aboutDoctorrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about doctor at least 20 letters and at most 200 letters arabic only.
        /// </summary>
        public static string aboutDoctorValidationAr {
            get {
                return ResourceManager.GetString("aboutDoctorValidationAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about doctor at least 20 letters and at most 200 letters english only.
        /// </summary>
        public static string aboutDoctorValidationEng {
            get {
                return ResourceManager.GetString("aboutDoctorValidationEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoor Doctor provides you with direct contact with a wide range of hospitals, access to prices and services, and the possibility of booking services.
        /// </summary>
        public static string aboutHospitals {
            get {
                return ResourceManager.GetString("aboutHospitals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoor Doctor provides you with a comprehensive guide to places of services and prices of laboratories and medical analysis near you with the possibility of electronic booking without trouble.
        /// </summary>
        public static string aboutLabAnalysis {
            get {
                return ResourceManager.GetString("aboutLabAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We provide you with comprehensive services to find out the availability of places in hospitals, hospitals, ambulances and medical supplies.
        /// </summary>
        public static string aboutOtherServices {
            get {
                return ResourceManager.GetString("aboutOtherServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoor Doctor provides you with a comprehensive guide to the places of pharmacies close to where you are and the services available without worrying about your presence in any place you do not know.
        /// </summary>
        public static string aboutPharmacies {
            get {
                return ResourceManager.GetString("aboutPharmacies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our site does not contain any files that infringe our property rights.
        /// </summary>
        public static string aboutPolicy {
            get {
                return ResourceManager.GetString("aboutPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoor Doctor provides you with a comprehensive guide to the location and services of the nearest radiation center from your place of residence as well as the electronic reservation service and saves you time and effort.
        /// </summary>
        public static string aboutRays {
            get {
                return ResourceManager.GetString("aboutRays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To improve your search results, please select an item from each section because if you do not select an item ,all search result will be appear to you..
        /// </summary>
        public static string aboutSearchnotice {
            get {
                return ResourceManager.GetString("aboutSearchnotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A company that aims to reach an integrated medical network through medical services and it is easy for the user to access it at the time he wants to sign information about the services and places of availability and prices and access to it without any trouble.
        /// </summary>
        public static string aboutTabeebakSite {
            get {
                return ResourceManager.GetString("aboutTabeebakSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advices.
        /// </summary>
        public static string advices {
            get {
                return ResourceManager.GetString("advices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advices page.
        /// </summary>
        public static string advicesPage {
            get {
                return ResourceManager.GetString("advicesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doctors advices page.
        /// </summary>
        public static string advicesPageTitle {
            get {
                return ResourceManager.GetString("advicesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree on.
        /// </summary>
        public static string agreeOn {
            get {
                return ResourceManager.GetString("agreeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All cities.
        /// </summary>
        public static string allCities {
            get {
                return ResourceManager.GetString("allCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All destricts.
        /// </summary>
        public static string allDestricts {
            get {
                return ResourceManager.GetString("allDestricts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All specialities.
        /// </summary>
        public static string allSpecialities {
            get {
                return ResourceManager.GetString("allSpecialities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This phone number is already exists.
        /// </summary>
        public static string alreadyNumerExist {
            get {
                return ResourceManager.GetString("alreadyNumerExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis Center.
        /// </summary>
        public static string anylisisCenter {
            get {
                return ResourceManager.GetString("anylisisCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to who are we??.
        /// </summary>
        public static string areWe {
            get {
                return ResourceManager.GetString("areWe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you new user?.
        /// </summary>
        public static string AreYouNewerUser {
            get {
                return ResourceManager.GetString("AreYouNewerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you registered already?.
        /// </summary>
        public static string areYouRegistered {
            get {
                return ResourceManager.GetString("areYouRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At The City Of.
        /// </summary>
        public static string atCityOf {
            get {
                return ResourceManager.GetString("atCityOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At The Destrict Of.
        /// </summary>
        public static string atDestrictOf {
            get {
                return ResourceManager.GetString("atDestrictOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The available time is required.
        /// </summary>
        public static string availableTimeRequired {
            get {
                return ResourceManager.GetString("availableTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The available time is at least 8 letters and at most 50 letters arabiconly.
        /// </summary>
        public static string availableTimeValidationAr {
            get {
                return ResourceManager.GetString("availableTimeValidationAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The available time is at least 8 letters and at most 50 letters english only.
        /// </summary>
        public static string availableTimeValidationEng {
            get {
                return ResourceManager.GetString("availableTimeValidationEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The available time is at least 8 letters and at most 50 letters.
        /// </summary>
        public static string avialableTimeLength {
            get {
                return ResourceManager.GetString("avialableTimeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your birth date is required.
        /// </summary>
        public static string birthDataIsRequired {
            get {
                return ResourceManager.GetString("birthDataIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string birthDate {
            get {
                return ResourceManager.GetString("birthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your booking is done.
        /// </summary>
        public static string bookingAppointDone {
            get {
                return ResourceManager.GetString("bookingAppointDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to booking appointement.
        /// </summary>
        public static string bookingAppointement {
            get {
                return ResourceManager.GetString("bookingAppointement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking date.
        /// </summary>
        public static string bookingDate {
            get {
                return ResourceManager.GetString("bookingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Details.
        /// </summary>
        public static string bookingDetails {
            get {
                return ResourceManager.GetString("bookingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking type is required.
        /// </summary>
        public static string bookingTypeRequired {
            get {
                return ResourceManager.GetString("bookingTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book online or call to.
        /// </summary>
        public static string bookOnlineOrCallOn {
            get {
                return ResourceManager.GetString("bookOnlineOrCallOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to book your appointement.
        /// </summary>
        public static string bookYourAppointement {
            get {
                return ResourceManager.GetString("bookYourAppointement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browsing The Speciality.
        /// </summary>
        public static string browsing_The_Speciality {
            get {
                return ResourceManager.GetString("browsing The Speciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Us.
        /// </summary>
        public static string callUs {
            get {
                return ResourceManager.GetString("callUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no permission for accessing this page ,you must be logged in first in order to access the page.
        /// </summary>
        public static string cannotAccessPageLoginFirst {
            get {
                return ResourceManager.GetString("cannotAccessPageLoginFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change password.
        /// </summary>
        public static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change your password.
        /// </summary>
        public static string changeYourPassword {
            get {
                return ResourceManager.GetString("changeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your city is required.
        /// </summary>
        public static string cityRequired {
            get {
                return ResourceManager.GetString("cityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic Address.
        /// </summary>
        public static string clinicAddress {
            get {
                return ResourceManager.GetString("clinicAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clinic address at least 10 letters.
        /// </summary>
        public static string clinicAddressLength {
            get {
                return ResourceManager.GetString("clinicAddressLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clinic address is required.
        /// </summary>
        public static string clinicAddressrequired {
            get {
                return ResourceManager.GetString("clinicAddressrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clinic address at least 10 letters arabic only.
        /// </summary>
        public static string clinicAddressValidationAr {
            get {
                return ResourceManager.GetString("clinicAddressValidationAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clinic address at least 10 letters english only.
        /// </summary>
        public static string clinicAddressValidationEng {
            get {
                return ResourceManager.GetString("clinicAddressValidationEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment.
        /// </summary>
        public static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your complaint has been sent and will be answered to you as soon as possible on your email.
        /// </summary>
        public static string complainDone {
            get {
                return ResourceManager.GetString("complainDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for submitting your suggesion.
        /// </summary>
        public static string complainThank {
            get {
                return ResourceManager.GetString("complainThank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete name.
        /// </summary>
        public static string completeName {
            get {
                return ResourceManager.GetString("completeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm password.
        /// </summary>
        public static string confirmPassword {
            get {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select valid destrict.
        /// </summary>
        public static string destrictnotValid {
            get {
                return ResourceManager.GetString("destrictnotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your destrict of city is required.
        /// </summary>
        public static string destrictRequired {
            get {
                return ResourceManager.GetString("destrictRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Download.
        /// </summary>
        public static string directDownload {
            get {
                return ResourceManager.GetString("directDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr..
        /// </summary>
        public static string doctoor {
            get {
                return ResourceManager.GetString("doctoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doctor.
        /// </summary>
        public static string doctor {
            get {
                return ResourceManager.GetString("doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor advices.
        /// </summary>
        public static string doctorAdvices {
            get {
                return ResourceManager.GetString("doctorAdvices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor title.
        /// </summary>
        public static string doctorEducation {
            get {
                return ResourceManager.GetString("doctorEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have informed the doctor with your booking.
        /// </summary>
        public static string doctorInformedWithBook {
            get {
                return ResourceManager.GetString("doctorInformedWithBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor name.
        /// </summary>
        public static string doctorName {
            get {
                return ResourceManager.GetString("doctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking a doctor.
        /// </summary>
        public static string doctorReserve {
            get {
                return ResourceManager.GetString("doctorReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doctors.
        /// </summary>
        public static string doctors {
            get {
                return ResourceManager.GetString("doctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor site.
        /// </summary>
        public static string doctorSite {
            get {
                return ResourceManager.GetString("doctorSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doctor visitors.
        /// </summary>
        public static string doctorVisits {
            get {
                return ResourceManager.GetString("doctorVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download our application now,and get freely and easely our services ,and save your time.
        /// </summary>
        public static string downloadAppDescription {
            get {
                return ResourceManager.GetString("downloadAppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Our App Now.
        /// </summary>
        public static string downloadAppNow {
            get {
                return ResourceManager.GetString("downloadAppNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select valid education.
        /// </summary>
        public static string educationNotValid {
            get {
                return ResourceManager.GetString("educationNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to education is required.
        /// </summary>
        public static string educationrequired {
            get {
                return ResourceManager.GetString("educationrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email link.
        /// </summary>
        public static string emailLink {
            get {
                return ResourceManager.GetString("emailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail is not valid.
        /// </summary>
        public static string emailNotValid {
            get {
                return ResourceManager.GetString("emailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is required.
        /// </summary>
        public static string emailRequired {
            get {
                return ResourceManager.GetString("emailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter booking data.
        /// </summary>
        public static string enterBookingData {
            get {
                return ResourceManager.GetString("enterBookingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter three words patient name.
        /// </summary>
        public static string enterFullPatientName {
            get {
                return ResourceManager.GetString("enterFullPatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter phone number.
        /// </summary>
        public static string EnterPhoneNumber {
            get {
                return ResourceManager.GetString("EnterPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter your phone number that you registered on Zoor Doctor.
        /// </summary>
        public static string enterRegisteredPhone {
            get {
                return ResourceManager.GetString("enterRegisteredPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter your username or email that you registered on Zoor Doctor.
        /// </summary>
        public static string enterRegisteredUsername {
            get {
                return ResourceManager.GetString("enterRegisteredUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter valid data.
        /// </summary>
        public static string enterValidData {
            get {
                return ResourceManager.GetString("enterValidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to examin fee at least 10 pounds.
        /// </summary>
        public static string examinfeeRang {
            get {
                return ResourceManager.GetString("examinfeeRang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examin fee is required.
        /// </summary>
        public static string examinFeeRequired {
            get {
                return ResourceManager.GetString("examinFeeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examin fee.
        /// </summary>
        public static string examinPrice {
            get {
                return ResourceManager.GetString("examinPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login by facebook account.
        /// </summary>
        public static string facebookLogin {
            get {
                return ResourceManager.GetString("facebookLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join us by facebook.
        /// </summary>
        public static string facebookRegister {
            get {
                return ResourceManager.GetString("facebookRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Search.
        /// </summary>
        public static string fastSearch {
            get {
                return ResourceManager.GetString("fastSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to female.
        /// </summary>
        public static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first name is invalid.
        /// </summary>
        public static string firstNameNotValid {
            get {
                return ResourceManager.GetString("firstNameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first name is required.
        /// </summary>
        public static string firstNamerequired {
            get {
                return ResourceManager.GetString("firstNamerequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name is at least 3 letters and at most 25 letters.
        /// </summary>
        public static string firstNameValidation {
            get {
                return ResourceManager.GetString("firstNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call us.
        /// </summary>
        public static string forCallUs {
            get {
                return ResourceManager.GetString("forCallUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you forgot password?.
        /// </summary>
        public static string forgotPassword {
            get {
                return ResourceManager.GetString("forgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from 100 to 200.
        /// </summary>
        public static string from100To200 {
            get {
                return ResourceManager.GetString("from100To200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from 50 to 100.
        /// </summary>
        public static string from50To100 {
            get {
                return ResourceManager.GetString("from50To100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string fullName {
            get {
                return ResourceManager.GetString("fullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gender.
        /// </summary>
        public static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Gender is required.
        /// </summary>
        public static string genderIsRequired {
            get {
                return ResourceManager.GetString("genderIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give your comment.
        /// </summary>
        public static string giveComment {
            get {
                return ResourceManager.GetString("giveComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login by gmail account.
        /// </summary>
        public static string googleLogin {
            get {
                return ResourceManager.GetString("googleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join us by gmail.
        /// </summary>
        public static string googleRegister {
            get {
                return ResourceManager.GetString("googleRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already a book on this doctor on the same day.
        /// </summary>
        public static string haveBookingAlready {
            get {
                return ResourceManager.GetString("haveBookingAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services help you.
        /// </summary>
        public static string helpingServices {
            get {
                return ResourceManager.GetString("helpingServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch the video by booking, recording and searching the site.
        /// </summary>
        public static string helpingVideos {
            get {
                return ResourceManager.GetString("helpingVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide comments.
        /// </summary>
        public static string hideComments {
            get {
                return ResourceManager.GetString("hideComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hospitals.
        /// </summary>
        public static string hospitals {
            get {
                return ResourceManager.GetString("hospitals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easly book with the best doctors in egypt by tabeebal .
        /// </summary>
        public static string indexTitle {
            get {
                return ResourceManager.GetString("indexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid personal data for reservation,patient name or phone data was invalid.
        /// </summary>
        public static string invalidBookingData {
            get {
                return ResourceManager.GetString("invalidBookingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dissection labs.
        /// </summary>
        public static string labAnalysis {
            get {
                return ResourceManager.GetString("labAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last name is invalid.
        /// </summary>
        public static string lastnameNotvalid {
            get {
                return ResourceManager.GetString("lastnameNotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last name is required.
        /// </summary>
        public static string lastNameRequired {
            get {
                return ResourceManager.GetString("lastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name is at least 3 letters and at most 25 letters.
        /// </summary>
        public static string lastnameValidation {
            get {
                return ResourceManager.GetString("lastnameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than 50.
        /// </summary>
        public static string less50 {
            get {
                return ResourceManager.GetString("less50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password rest link has expired or invalid.
        /// </summary>
        public static string linkExpired {
            get {
                return ResourceManager.GetString("linkExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string loginHeading {
            get {
                return ResourceManager.GetString("loginHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Now.
        /// </summary>
        public static string loginNow {
            get {
                return ResourceManager.GetString("loginNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string logOut {
            get {
                return ResourceManager.GetString("logOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to male.
        /// </summary>
        public static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Profile.
        /// </summary>
        public static string manageProfile {
            get {
                return ResourceManager.GetString("manageProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you have maximum of two times of booking at the same day for the same doctor.
        /// </summary>
        public static string maxBookingNumber {
            get {
                return ResourceManager.GetString("maxBookingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A group of top university professors and consultants, know how people evaluate them and book online.
        ///Immediate booking at 2000 Doctor · Know people&apos;s assessment of doctors · Book online or call 16676
        ///Services: Know the check price before booking, free immediate booking, know waiting time at the clinic.
        /// </summary>
        public static string metaDescription {
            get {
                return ResourceManager.GetString("metaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tabeebak,book a doctor,book a clinic,book the best doctor,book with tabeebak,find the best doctor in egypt,book and find doctor,get the best doctor,find doctor,find clinic,Zoor Doctor.
        /// </summary>
        public static string metaKeywords {
            get {
                return ResourceManager.GetString("metaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string minute {
            get {
                return ResourceManager.GetString("minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more than 200.
        /// </summary>
        public static string more100 {
            get {
                return ResourceManager.GetString("more100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving to the service of.
        /// </summary>
        public static string moveToService {
            get {
                return ResourceManager.GetString("moveToService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Appointements.
        /// </summary>
        public static string myAppointement {
            get {
                return ResourceManager.GetString("myAppointement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new password.
        /// </summary>
        public static string newPassword {
            get {
                return ResourceManager.GetString("newPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next visites appointements.
        /// </summary>
        public static string nextAppointement {
            get {
                return ResourceManager.GetString("nextAppointement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no visits for you untill now..
        /// </summary>
        public static string noAppointementBefor {
            get {
                return ResourceManager.GetString("noAppointementBefor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can not find this phone number that you registered in the Zoor Doctor account,please enter valid phone number.
        /// </summary>
        public static string noDataAboutPhone {
            get {
                return ResourceManager.GetString("noDataAboutPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can not find any username or e-mail that you registered in the Zoor Doctor account,please enter valid username or e-mail.
        /// </summary>
        public static string noDataAboutUsernameOrEmail {
            get {
                return ResourceManager.GetString("noDataAboutUsernameOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;re no doctors in this speciality untill now.
        /// </summary>
        public static string noDoctorsInSpeciality {
            get {
                return ResourceManager.GetString("noDoctorsInSpeciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results match search items.
        /// </summary>
        public static string noResultMatch {
            get {
                return ResourceManager.GetString("noResultMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string notice {
            get {
                return ResourceManager.GetString("notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no waiting before entrance to doctor.
        /// </summary>
        public static string noWaiting {
            get {
                return ResourceManager.GetString("noWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one doctor.
        /// </summary>
        public static string onlyOneDoctor {
            get {
                return ResourceManager.GetString("onlyOneDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only two doctors.
        /// </summary>
        public static string onlyTwoDoctors {
            get {
                return ResourceManager.GetString("onlyTwoDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or Select Doctor Name.
        /// </summary>
        public static string orSelectDoctorname {
            get {
                return ResourceManager.GetString("orSelectDoctorname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Pages.
        /// </summary>
        public static string otherPages {
            get {
                return ResourceManager.GetString("otherPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other services.
        /// </summary>
        public static string otherServices {
            get {
                return ResourceManager.GetString("otherServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to our services.
        /// </summary>
        public static string ourServices {
            get {
                return ResourceManager.GetString("ourServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services provided by Zoor Doctor.
        /// </summary>
        public static string ourServicesForYou {
            get {
                return ResourceManager.GetString("ourServicesForYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page that you search for is not found.
        /// </summary>
        public static string pageNotFound {
            get {
                return ResourceManager.GetString("pageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string pages {
            get {
                return ResourceManager.GetString("pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string passString {
            get {
                return ResourceManager.GetString("passString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoor Doctor-Password Recovery.
        /// </summary>
        public static string passwordRecoveryTitleToEmail {
            get {
                return ResourceManager.GetString("passwordRecoveryTitleToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password  is required.
        /// </summary>
        public static string passwordRequired {
            get {
                return ResourceManager.GetString("passwordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at least one number, one lowercase , one uppercase letter at least six characters and at most 20 characters.
        /// </summary>
        public static string passwordValidation {
            get {
                return ResourceManager.GetString("passwordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient name.
        /// </summary>
        public static string patientName {
            get {
                return ResourceManager.GetString("patientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to patient name is required.
        /// </summary>
        public static string patientNameIsRequired {
            get {
                return ResourceManager.GetString("patientNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal communication.
        /// </summary>
        public static string personalCommunication {
            get {
                return ResourceManager.GetString("personalCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to personal image is not valid.
        /// </summary>
        public static string personalImgNotValid {
            get {
                return ResourceManager.GetString("personalImgNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The personal Image is required.
        /// </summary>
        public static string personalImgrequired {
            get {
                return ResourceManager.GetString("personalImgrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacies.
        /// </summary>
        public static string pharmacies {
            get {
                return ResourceManager.GetString("pharmacies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmay.
        /// </summary>
        public static string pharmacy {
            get {
                return ResourceManager.GetString("pharmacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This phone number is already reserved.
        /// </summary>
        public static string phoneISAlreadyExists {
            get {
                return ResourceManager.GetString("phoneISAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone format is not valid.
        /// </summary>
        public static string phoneNotValid {
            get {
                return ResourceManager.GetString("phoneNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string phoneNumber {
            get {
                return ResourceManager.GetString("phoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Required.
        /// </summary>
        public static string phoneRequired {
            get {
                return ResourceManager.GetString("phoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click on this link to change your password.
        /// </summary>
        public static string pleaseClickOnLinkToChangePassword {
            get {
                return ResourceManager.GetString("pleaseClickOnLinkToChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter complete name.
        /// </summary>
        public static string pleaseEnterCpompleteName {
            get {
                return ResourceManager.GetString("pleaseEnterCpompleteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter phone to complete your data.
        /// </summary>
        public static string pleaseEnterPhone {
            get {
                return ResourceManager.GetString("pleaseEnterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number.
        /// </summary>
        public static string portablePhoneNumber {
            get {
                return ResourceManager.GetString("portablePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pound.
        /// </summary>
        public static string pound {
            get {
                return ResourceManager.GetString("pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previos visites appointements.
        /// </summary>
        public static string prevAppointement {
            get {
                return ResourceManager.GetString("prevAppointement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string privacy {
            get {
                return ResourceManager.GetString("privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string privacyPolicy {
            get {
                return ResourceManager.GetString("privacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem occured during executing operation on server.
        /// </summary>
        public static string problemOnDoingOperationAtServer {
            get {
                return ResourceManager.GetString("problemOnDoingOperationAtServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem occured during sending reset link to your email,please try again.
        /// </summary>
        public static string problemOnSendingResetLink {
            get {
                return ResourceManager.GetString("problemOnSendingResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profission Image is required.
        /// </summary>
        public static string professionImagerequired {
            get {
                return ResourceManager.GetString("professionImagerequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profession title is required.
        /// </summary>
        public static string professiontitleisrequired {
            get {
                return ResourceManager.GetString("professiontitleisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profession title at least 10 letters and at most 150 letters.
        /// </summary>
        public static string professiontitleLength {
            get {
                return ResourceManager.GetString("professiontitleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profession title at least 10 letters and at most 150 letters arabic only.
        /// </summary>
        public static string professiontitleValidationAr {
            get {
                return ResourceManager.GetString("professiontitleValidationAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profession title at least 10 letters and at most 150 letters english only.
        /// </summary>
        public static string professiontitleValidationEng {
            get {
                return ResourceManager.GetString("professiontitleValidationEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string profilePage {
            get {
                return ResourceManager.GetString("profilePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiation Center.
        /// </summary>
        public static string rayCenter {
            get {
                return ResourceManager.GetString("rayCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiology Centers.
        /// </summary>
        public static string raysCenter {
            get {
                return ResourceManager.GetString("raysCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration is faild.
        /// </summary>
        public static string registerFaild {
            get {
                return ResourceManager.GetString("registerFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration method.
        /// </summary>
        public static string registerMethod {
            get {
                return ResourceManager.GetString("registerMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remember me.
        /// </summary>
        public static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reservation type is required.
        /// </summary>
        public static string reservationtyperequired {
            get {
                return ResourceManager.GetString("reservationtyperequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book now.
        /// </summary>
        public static string reserveNow {
            get {
                return ResourceManager.GetString("reserveNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Method.
        /// </summary>
        public static string reservingMethod {
            get {
                return ResourceManager.GetString("reservingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrieve my password by sending reset link on my registered email to reset password.
        /// </summary>
        public static string retrievePasswordByEmail {
            get {
                return ResourceManager.GetString("retrievePasswordByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrieve password by sending message to my registered phone to change password.
        /// </summary>
        public static string retrievePasswordByPhone {
            get {
                return ResourceManager.GetString("retrievePasswordByPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights are reserved for Zoor Doctor team work.
        /// </summary>
        public static string rightReserverdForTabeebakUsers {
            get {
                return ResourceManager.GetString("rightReserverdForTabeebakUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles and constraints.
        /// </summary>
        public static string rolesAndCondictions {
            get {
                return ResourceManager.GetString("rolesAndCondictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rules and conditions-Zoor Doctor.
        /// </summary>
        public static string rulesAndConditions {
            get {
                return ResourceManager.GetString("rulesAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Data.
        /// </summary>
        public static string saveData {
            get {
                return ResourceManager.GetString("saveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look for advice in a specialty or doctor.
        /// </summary>
        public static string searchForAdvice {
            get {
                return ResourceManager.GetString("searchForAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for doctor or speciality using quick search.
        /// </summary>
        public static string searchForDocOrSpByquichSearch {
            get {
                return ResourceManager.GetString("searchForDocOrSpByquichSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search for doctor or call us 19666.
        /// </summary>
        public static string searchForDoctorOrCall {
            get {
                return ResourceManager.GetString("searchForDoctorOrCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching For Doctor.
        /// </summary>
        public static string searchingForDoc {
            get {
                return ResourceManager.GetString("searchingForDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching For Speciality.
        /// </summary>
        public static string searchingForSpeciality {
            get {
                return ResourceManager.GetString("searchingForSpeciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search method.
        /// </summary>
        public static string searchMethod {
            get {
                return ResourceManager.GetString("searchMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string searchResult {
            get {
                return ResourceManager.GetString("searchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one sub speciality.
        /// </summary>
        public static string selectAtLeastOneSubSpeciality {
            get {
                return ResourceManager.GetString("selectAtLeastOneSubSpeciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select city.
        /// </summary>
        public static string selectCity {
            get {
                return ResourceManager.GetString("selectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Destrict.
        /// </summary>
        public static string selectDestrict {
            get {
                return ResourceManager.GetString("selectDestrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or Select Doctor Name.
        /// </summary>
        public static string selectDocName {
            get {
                return ResourceManager.GetString("selectDocName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select speciality.
        /// </summary>
        public static string selectSpeciality {
            get {
                return ResourceManager.GetString("selectSpeciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send code to mobile.
        /// </summary>
        public static string sendCodeToMobile {
            get {
                return ResourceManager.GetString("sendCodeToMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with the server you can try later.
        /// </summary>
        public static string serverProblem {
            get {
                return ResourceManager.GetString("serverProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share this advice on facebook.
        /// </summary>
        public static string shareAdviceTitle {
            get {
                return ResourceManager.GetString("shareAdviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join us.
        /// </summary>
        public static string signHeading {
            get {
                return ResourceManager.GetString("signHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join us now.
        /// </summary>
        public static string signNow {
            get {
                return ResourceManager.GetString("signNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join us.
        /// </summary>
        public static string signUp {
            get {
                return ResourceManager.GetString("signUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to social communication.
        /// </summary>
        public static string socialCommunication {
            get {
                return ResourceManager.GetString("socialCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Specialities.
        /// </summary>
        public static string Specialities {
            get {
                return ResourceManager.GetString("Specialities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciality of.
        /// </summary>
        public static string speciality {
            get {
                return ResourceManager.GetString("speciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select valid speciality.
        /// </summary>
        public static string specialityNotValid {
            get {
                return ResourceManager.GetString("specialityNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciality is required.
        /// </summary>
        public static string specialityrequired {
            get {
                return ResourceManager.GetString("specialityrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specialised doctors.
        /// </summary>
        public static string specializedDoctors {
            get {
                return ResourceManager.GetString("specializedDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoor Doctor.
        /// </summary>
        public static string tabeebak {
            get {
                return ResourceManager.GetString("tabeebak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoor Doctor site.
        /// </summary>
        public static string tabeebakWebsite {
            get {
                return ResourceManager.GetString("tabeebakWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my appointements with Zoor Doctor.
        /// </summary>
        public static string titleAppointements {
            get {
                return ResourceManager.GetString("titleAppointements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking details.
        /// </summary>
        public static string titleBookingDetails {
            get {
                return ResourceManager.GetString("titleBookingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoor Doctor-change your password.
        /// </summary>
        public static string titleChangePassword {
            get {
                return ResourceManager.GetString("titleChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doctor page on Zoor Doctor.
        /// </summary>
        public static string titleDoctorPage {
            get {
                return ResourceManager.GetString("titleDoctorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search for the best doctors with Zoor Doctor.
        /// </summary>
        public static string titleFastSearch {
            get {
                return ResourceManager.GetString("titleFastSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join to Zoor Doctor.
        /// </summary>
        public static string titleJoin {
            get {
                return ResourceManager.GetString("titleJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to Zoor Doctor.
        /// </summary>
        public static string titleLogin {
            get {
                return ResourceManager.GetString("titleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy policy-Zoor Doctor.
        /// </summary>
        public static string titlePrivacy {
            get {
                return ResourceManager.GetString("titlePrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile on Zoor Doctor.
        /// </summary>
        public static string titleProfile {
            get {
                return ResourceManager.GetString("titleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoor Doctor-remember password.
        /// </summary>
        public static string titleRememerPassword {
            get {
                return ResourceManager.GetString("titleRememerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to booking details.
        /// </summary>
        public static string titleReservingDetailPage {
            get {
                return ResourceManager.GetString("titleReservingDetailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thank you for booking.
        /// </summary>
        public static string titleReservingDonePage {
            get {
                return ResourceManager.GetString("titleReservingDonePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search for your doctor with Zoor Doctor.
        /// </summary>
        public static string titleSearch {
            get {
                return ResourceManager.GetString("titleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specialities page.
        /// </summary>
        public static string titleSpecialities {
            get {
                return ResourceManager.GetString("titleSpecialities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speciality browsing.
        /// </summary>
        public static string titleSpecialityBrows {
            get {
                return ResourceManager.GetString("titleSpecialityBrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thank you for your booking.
        /// </summary>
        public static string titleThankBooking {
            get {
                return ResourceManager.GetString("titleThankBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string today {
            get {
                return ResourceManager.GetString("today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        public static string tomorrow {
            get {
                return ResourceManager.GetString("tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile update has been faild,please validate your data.
        /// </summary>
        public static string updateProfileFaild {
            get {
                return ResourceManager.GetString("updateProfileFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to url format is not valid.
        /// </summary>
        public static string urlNotValid {
            get {
                return ResourceManager.GetString("urlNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string userName {
            get {
                return ResourceManager.GetString("userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username is  already exists.
        /// </summary>
        public static string userNameIsAlreadyExists {
            get {
                return ResourceManager.GetString("userNameIsAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter valid username between 3 and 16 letters.
        /// </summary>
        public static string userNameMinimumLength {
            get {
                return ResourceManager.GetString("userNameMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username or password not valid.
        /// </summary>
        public static string userNameOrPasswordNotValid {
            get {
                return ResourceManager.GetString("userNameOrPasswordNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username is required.
        /// </summary>
        public static string usernameRequired {
            get {
                return ResourceManager.GetString("usernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor.
        /// </summary>
        public static string visitor {
            get {
                return ResourceManager.GetString("visitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visit to doctor is based on priority of attendance at your booked interval.
        /// </summary>
        public static string visitPriorityToDoctor {
            get {
                return ResourceManager.GetString("visitPriorityToDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting before entrance to doctor.
        /// </summary>
        public static string waitingTime {
            get {
                return ResourceManager.GetString("waitingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting time required.
        /// </summary>
        public static string waitingTimerequired {
            get {
                return ResourceManager.GetString("waitingTimerequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoor Doctor Statistics.
        /// </summary>
        public static string websiteStatis {
            get {
                return ResourceManager.GetString("websiteStatis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcom.
        /// </summary>
        public static string welcom {
            get {
                return ResourceManager.GetString("welcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we remember you that your username is.
        /// </summary>
        public static string weRememberYouUsername {
            get {
                return ResourceManager.GetString("weRememberYouUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What you are looking for?.
        /// </summary>
        public static string whatSearch {
            get {
                return ResourceManager.GetString("whatSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Doctor Serve You Any Time.
        /// </summary>
        public static string withYouAnyWhere {
            get {
                return ResourceManager.GetString("withYouAnyWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select doctor name.
        /// </summary>
        public static string writeDoctorName {
            get {
                return ResourceManager.GetString("writeDoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your message.
        /// </summary>
        public static string yourMessage {
            get {
                return ResourceManager.GetString("yourMessage", resourceCulture);
            }
        }
    }
}
